language: go

env:
  - GO_OS=linux GO_ARCH=amd64
  - GO_OS=darwin GO_ARCH=amd64
  - GO_OS=windows GO_ARCH=amd64
  - GO_OS=windows GO_ARCH=386

script:
  - GOOS=${GO_OS} GOARCH=${GO_ARCH} go build -o mackerel-plugin-check-whois
  - zip mackerel-plugin-check-whois_${GO_OS}_${GO_ARCH}.zip mackerel-plugin-check-whois

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: mackerel-plugin-check-whois_*.zip
  on:
    tag: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
