language: go

install:
  - go get

script:
  - go build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: mackerel-plugin-check-whois
  on:
    tag: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
